### ISSUE TITLE
New name for ServerClient

### ISSUE THREAD

**Issue by vladqwerty435** [tom-weiland/RiptideNetworking#1]
I think, RemoteClient better than current ServerClient

**Comment by tom-weiland** [comment]
I'm not so sure—"RemoteClient" seems to make more sense at first glance, but it's not really accurate. That class is responsible for handling the connection _to_ a remote client, but it isn't a remote client itself.

By the same logic, a local endpoint (the IP and port an application is listening on) should be referred to as the _remote_ endpoint instead, or am I thinking about this wrong?

I would've just called it "Client", but then we'd obviously have 2 classes with the same name. "ServerClient" seems like a relatively accurate name to me, so I think I'll need some convincing to change it :P

**Comment by vladqwerty435** [comment]
Okey:
RemoteConnection
RemoteClientConnection
ClientConnection

**Comment by tom-weiland** [comment]
ClientConnection is probably the best candidate of those, but the Client class also represents a client connection, and it'd be weird to have a ClientConnection class and then a Client class. That gets confusing—I still think ServerClient is best just because it tells you in the name that it represents a client on the server-side of things.
