### ISSUE TITLE
Change package manager header to "Other" 

### ISSUE THREAD

**Issue by RandomPadestrian** [tom-weiland/RiptideNetworking#14]
A quick suggestion for simplicity, since the author's name, is already labeled in the main view the category should be changed to "Other".

> Others

- RiptideNetworking
- Tweens
- etc...

![Screenshot 2022-01-09 204716](https://user-images.githubusercontent.com/97208166/148712888-69fa0bd6-1808-4350-afe0-c55929e7622f.png)

**Comment by tom-weiland** [comment]
> since the author's name, is already labeled in the main view

I'm assuming you're talking about the dropdowns on the right, with the "category" you're referring to being *Unity Technologies* for most of the packages visible in that screenshot?

If so, I don't think there's anything I can do to change that. If you look at the [package.json](https://github.com/tom-weiland/RiptideNetworking/blob/main/UnityPackage/package.json) (which is where the package manager gets all the info from to display), the only part that mentions my name as it's displayed on the right is the `author` tag:

```
"author": {
  "name": "Tom Weiland",
  "email": "contact@tomweiland.net",
  "url": "https://www.youtube.com/c/TomWeiland"
},
```

There's nothing like a `category` tag there that I could change, and Unity's [documentation for package manifest files](https://docs.unity3d.com/Manual/upm-manifestPkg.html) doesn't mention the existence of such a tag either. If you're aware of some undocumented way to set the category, let me know, but I actually think it makes a lot of sense for packages to be grouped by author.

If I had to guess, the reason your Tweens package in that screenshot is displayed under "Other" is because the author isn't specified in its manifest.
