### ISSUE TITLE
Add the ability to include custom data on server kicks.

### ISSUE THREAD

**Issue by Johnscaban** [tom-weiland/RiptideNetworking#20]
In Riptide v1.2.0, you added the ability to include custom data in connection attempts. I think it would be very useful to be able to include custom data when the server kicks a client. For example, to include a reason for the kick.

**Comment by ERmilburn02** [comment]
You could send them a packet first and then kick them.

**Comment by Johnscaban** [comment]
Yeah, but how would you guarantee that the packet reaches the client first?
```
SendKickReason(fromClientId);
Server.DisconnectClient(fromClientId);
```
If Server.DisconnectClient() makes it first, I think the reason will not make it.

**Comment by tom-weiland** [comment]
> I think it would be very useful to be able to include custom data when the server kicks a client. For example, to include a reason for the kick.

I could add that, but it would have a similar problem as a custom message—I can't guarantee delivery of a disconnect packet because the connection is closed right after it is sent, so if it gets lost there's no way to resend it (and it will result in the other end just timing out eventually).

Do you have anything in mind (regarding what data you would send) other than a reason for the disconnection? Because if the goal is just to include a reason, I'll probably let you pass an int (which can act as an ID for a disconnection reason, or various other things) instead of a full-blown message instance.

**Comment by tom-weiland** [comment]
> But isn't the disconnect packet, a message, to which, one could add values?

Yes, but doing so would require writing more code (you have to create a message, add the values, and then read the values on the other end) than simply passing an int to the DisconnectClient method which then could be returned to you in the Disconnected event.

Basically, if there's no need for flexibility in what data is being included (which doesn't seem to be the case, as everyone who has requested this wants it just to include a reason for the disconnection), then there's no sense in making everyone write a bunch of boilerplate code that would only be necessary to support that flexibility (which no one seems to need).

**Comment by Johnscaban** [comment]
> Basically, if there's no need for flexibility in what data is being included (which doesn't seem to be the case, as everyone who has requested this wants it just to include a reason for the disconnection), then there's no sense in making everyone write a bunch of boilerplate code that would only be necessary to support that flexibility (which no one seems to need).

Ok, I get your point. Passing an int or something else would work. 

If you implement this, it would be great and useful.

Thanks for listening to feedback, and keep up the good work!

**Comment by tom-weiland** [comment]
I know it's been a while, but I've thought about this further, and given that Steam's networking takes a string for the disconnect reason, I'm considering just letting you pass a string to the `DisconnectClient` method. Normally it would be preferable to send an ID instead of a full-blown string, but kicking a player happens rarely enough that it won't be a bandwidth issue.

Using a string also has the added benefit of supporting dynamic/not hard-coded reasons, such as in the case where a server admin enters a kick command along with a custom reason.

The one drawback I can see is that it obviously doesn't allow for custom data to be added (at least not without converting it to a string), although at this point I can't think of a scenario where that'd be necessary 🤔

**Comment by Johnscaban** [comment]
> I'm considering just letting you pass a string to the DisconnectClient method.

Yeah, that works just fine.

> The one drawback I can see is that it obviously doesn't allow for custom data to be added (at least not without converting it to a string), although at this point I can't think of a scenario where that'd be necessary 🤔

I don't think its necessary to be able to include custom data. The string should work just fine. Besides, I also haven't been able to come up with a scenario where it would be necessary.

PS: Sorry for the late reply, didn't see yours.

**Comment by tom-weiland** [comment]
> I also haven't been able to come up with a scenario where it would be necessary.

If it turns out that it _is_ necessary for something, I can always add an overload that allows it in a future update.
