### ISSUE TITLE
How to use LanDiscovery?

### ISSUE THREAD

**Issue by yogioh123456** [tom-weiland/RiptideNetworking#29]
i dont know how to use, is need a example?

**Comment by tom-weiland** [comment]
Create a `LanDiscovery` instance on both the client and server. On the server, call `StartListening`. On the client, subscribe to the `HostDiscovered` event, call `SendBroadcast`, and make sure `Tick` is being called in `FixedUpdate` (assuming you're using Unity) somewhere.

**Comment by MrCelsius88** [comment]
Would the steps be the same in a peer-to-peer solution?

**Comment by tom-weiland** [comment]
> Would the steps be the same in a peer-to-peer solution?

That depends on what you mean by peer-to-peer.

If you're talking about _real_ peer-to-peer where you have all clients connected to each other and all running the simulation (no one is acting as the server), then no, the steps would not be the same because you'd need to discover _all_ of the clients that are part of that peer-to-peer network.

If you're instead talking about one player hosting the game and everyone else connecting to just that one player (aka "player-hosted," often mistakenly referred to as "peer-to-peer"), then yes, the steps are the same because that's the situation the original steps were for. LAN discovery is pretty much pointless for anything related to dedicated servers.
