### ISSUE TITLE
LanDiscovery being blocked by windows firewall

### ISSUE THREAD

**Issue by MrCelsius88** [tom-weiland/RiptideNetworking#36]
Windows firewall appears to be blocking my game using that is using LAN discovery, is there any workaround to this that is not manually letting the game through the firewall? I don’t want users who are not system admins to not be able to use multiplayer. Also, does LAN discovery work on the same machine? Like if I started a client and server instance on the same machine, would they find each other?

**Comment by tom-weiland** [comment]
> I don’t want users who are not system admins to not be able to use multiplayer

There's nothing you can do about that as far as I know. Applications communicating through the internet is a potential security risk, which is why you need admin access to allow things through the firewall. If there was a way around that, it would be kind of concerning.

Also, if someone doesn't have admin permissions and their computer's admin doesn't want to let your project through the firewall, it's likely not a computer they should be playing games on anyways :P

> Also, does LAN discovery work on the same machine?

That should work fine, but couldn't you have just tried it? You would have had your answer much quicker...

**Comment by MrCelsius88** [comment]
> That should work fine, but couldn't you have just tried it? You would have had your answer much quicker...

I did try it and it didn’t work, thats why I was wondering. Anyway thanks for the response!

**Comment by tom-weiland** [comment]
> it didn’t work

That's very strange, especially considering the LanDiscovery class was mainly tested with the host and client on the same machine 🤔

**Comment by MrCelsius88** [comment]
Yeah, obviously I could be doing it wrong but I followed the same steps as in this issue
#29

**Comment by tom-weiland** [comment]
Your project is allowed through your firewall right? What does "it didn't work" actually mean? Are you getting errors? Just nothing being detected?

You may want to join the Discord server, as debugging stuff like this is easier over there.

**Comment by MrCelsius88** [comment]
Yeah no it’s just that nothing is getting detected, no errors or anything, I’ll close this issue because we already discussed that there is no real solution besides allowing it through the firewall. Thank you again for all the help.

**Comment by tom-weiland** [comment]
Well if nothing is being detected, you're presumably doing something wrong, so there _should_ be a solution :P
