### ISSUE TITLE
DisconnectedEventArgs is missing from namespace

### ISSUE THREAD

**Issue by Yuehin** [tom-weiland/RiptideNetworking#46]
Trying to implement a `DidDisconnect` function with a `DisconnectedEventArgs` argument (as like in the demo scripts) throws a "type or namespace could not be found" error. Could be that the class was not defined in the 1.2.0 build?

**Comment by tom-weiland** [comment]
The `DisconnectedEventArgs` stuff was added after v1.2.0 (270591cd5b04bd8143980b27d364e7bcc6d20786) and will be part of v1.3.0. The demos double as my test projects and are already using an updated version of the dll, which is why they can access the `DisconnectedEventArgs` class without errors.

If you want to use this functionality before v1.3.0 is released, you'll have to grab the dll from one of the demo projects and use that instead of the Unity package.
