### ISSUE TITLE
Client not receiving message if it sends a message on Start() and expects to receive message from Server

### ISSUE THREAD

**Issue by ameel** [tom-weiland/RiptideNetworking#48]
Setup:
1. On client, I have a unity script with `Start()` that connects to Server and sends a message.
2. The Server sends a response back to the client
3. The Client handles the message using `[MessageHandler]` in the same unity script above.

When client sends the message from Start(), it never receives the Server's response. 

Instead if I use a button to send message to server, client receives the message correctly. It seems to me that the Server is sending a response back to client before client has time to setup the [MessageHandler]. Or am I missing something?

Grateful for any insight.

Thank you!

Edit:
I moved the code for Client to send message from `Start()` into `Update()`, and use a bool to make sure it's only sent once. This seems to work (i.e. Client receives the response from Server), but it remains unclear why Client won't receive response from Server if it sends messag from `Start()`

**Comment by tom-weiland** [comment]
> it remains unclear why Client won't receive response from Server if it sends messag from `Start()`

Probably because connecting doesn't happen instantly—if you put a `Debug.Log` after the the `Connect` call in the `Start` method, you should see that log being printed before the "connected successfully" log. Messages that you send before you're connected won't go through.

If you want to send a message as soon as you connect, you should make use of the client's `Connected` event.

**Comment by ameel** [comment]
Thanks for the suggestion. I'll test and report

**Comment by ameel** [comment]
Indeed. That was the issue. Thanks
