### ISSUE TITLE
Message contains insufficient unread bytes (3) to read type 'int', returning 0!

### ISSUE THREAD

**Issue by BabyWhite69** [tom-weiland/RiptideNetworking#6]
Hi, I encountered this error when I was testing the demos, Unity-Client and Unity-Server work fine, the problem is when I connect Unity-Client with Console-Server, I get the following error:
![image](https://user-images.githubusercontent.com/80644505/123615518-60616900-d7d3-11eb-9618-e406ac36b218.png)
![image](https://user-images.githubusercontent.com/80644505/123615550-68b9a400-d7d3-11eb-8fce-eb7ee6fdfa17.png)
I made no modifications at all, I just opened it and ran it.

```(ERROR): Message contains insufficient unread bytes (1) to read type 'float', returning 0!
UnityEngine.Debug:Log (object)
RiptideNetworking.RiptideLogger:Log (string,string)
RiptideNetworking.Message:GetFloat ()
MessageExtensions:GetVector3 (RiptideNetworking.Message) (at Assets/Scripts/Multiplayer/MessageExtensions.cs:45)
ClientHandle:SpawnPlayer (RiptideNetworking.Message) (at Assets/Scripts/Multiplayer/ClientHandle.cs:10)
NetworkManager:MessageReceived (object,RiptideNetworking.ClientMessageReceivedEventArgs) (at Assets/Scripts/Multiplayer/NetworkManager.cs:110)
RiptideNetworking.Client:OnMessageReceived (RiptideNetworking.ClientMessageReceivedEventArgs)
RiptideNetworking.Client/<>c__DisplayClass37_0:<Handle>b__0 ()
RiptideNetworking.ActionQueue:ExecuteAll ()
NetworkManager:FixedUpdate () (at Assets/Scripts/Multiplayer/NetworkManager.cs:74)```

**Comment by ERmilburn02** [comment]
The 2 demos aren't compatible with each other.

**Comment by tom-weiland** [comment]
> Unity-Client and Unity-Server work fine, the problem is when I connect Unity-Client with Console-Server, I get the following error

@ERmilburn02 is correct. If by "Console-Server" you mean the server application from the console demos, and not the Unity server running in server build mode, then that's the problem. The console and Unity demos are _not_ built to work with each other—they do completely different things.

The console demos send a bunch of test messages back and forth, whereas the Unity demos have basic player movement set up. Since they send and receive different data, they won't be able to connect to each other without issues, as they'll be expecting a different message structure from what they'll actually receive.

**Comment by BabyWhite69** [comment]
Ohh, I understand, thanks for the explanation. @tom-weiland @ERmilburn02
