### ISSUE TITLE
Error on port parse

### ISSUE THREAD

**Issue by DesertFoxHU** [tom-weiland/RiptideNetworking#61]
I get an error while trying to join a server: (CLIENT): Invalid host address '192.168.1.180​:6112'! IP and port should be separated by a colon, for example: '127.0.0.1:7777'.

After a bit of debugging I found out the ushort.TryParse() segment gives error.
```csharp
if (!IPAddress.TryParse(ipString, out ip) || !ushort.TryParse(portString, out port))
{
  RiptideLogger.Log(LogType.error, LogName, $"Invalid host address '{hostAddress}'! IP and port should be separated by a colon, for example: '127.0.0.1:7777'.");
  port = 0;
  return false;
}
```
<br>

The whole thing is weird, because if you connect with `Client.Connect($"192.168.1.180:6112");` it works perfectly fine, so probably this will be an issue with .NET or with something else, but I thought I try here first.

**Comment by tom-weiland** [comment]
> The whole thing is weird, because if you connect with `Client.Connect($"192.168.1.180:6112");` it works perfectly fine

So if this "works perfectly fine," but you're getting an error which is displaying the exact same IP, what is the difference between the scenario where it works and where you get the error? Are you doing anything differently?

**Comment by DesertFoxHU** [comment]
![kép](https://user-images.githubusercontent.com/40893862/183309682-d61901e0-4410-4080-9cd1-e569e3cd629c.png)

And this is what I get:
![kép](https://user-images.githubusercontent.com/40893862/183309695-41d37af4-61a2-4e94-8b75-b9eb68c52653.png)

Line 54 is: `NetworkManager.Instance.port = ushort.Parse(ipAddress.Split(':')[1]);`

**Comment by tom-weiland** [comment]
Okay so even in your own code, the parse is failing on the port, which tells me that something is wrong with the piece of the string that should contain the port number and this almost certainly is not an issue with Riptide.

I think others have had issues when grabbing the IP & port from an input field (particularly with TMP input fields if I remember correctly—I believe the regular input fields don't have this issue) because it somehow added invisible/zero-width characters, which would prevent the parse from succeeding.

**Comment by DesertFoxHU** [comment]
You're right, but it was a bit weirder than that.

So you should use `TMP_InputField` instead of `TextMeshProUGUI` when working with IFs.
And yeah, every text from the input field needs to be trimmed with `text.Trim()`.

Thank you for your help, when even this wasn't related to this project.
