### ISSUE TITLE
Not being able to see error occured on Client.Connect

### ISSUE THREAD

**Issue by CodeEasyYT** [tom-weiland/RiptideNetworking#8]
This is just a feature request, but it would be nice if we can view the problem when connecting the server on `Client.ConnectionFailed`.

I didn't opened a pull request because I have no idea how this works.

**Comment by tom-weiland** [comment]
> it would be nice if we can view the problem when connecting the server on `Client.ConnectionFailed`.

The `ConnectionFailed` event is invoked when the client has tried to connect `maxConnectionAttempts` (defaults to 5, but the `Connect` method has an optional parameter that you can set if you need to change it) times without receiving a response.

This can happen for several reasons, including not having an internet connection or trying to connect to an IP & port that no server is listening on (whether it's because you put in an incorrect IP or port or you just forgot to start the server). However, Riptide has no concept of _why_ the server didn't respond, as that's simply not information that's available.

If you want something to display to the user, I suppose any time the `ConnectionFailed` event is invoked it means the connection attempt timed out. I can make that clear in the xml documentation for the event, but if you've got any other suggestions regarding this, let me know :)

**Comment by CodeEasyYT** [comment]
Yes an XML documentation detail would be nice. I had no idea that UDP and Riptide can not understand *why* it was not able to connect.

I guess I'm just going to pretend and lie to the player about "timed out" message. Thanks for the fast response!

**Comment by tom-weiland** [comment]
> I guess I'm just going to pretend and lie to the player about "timed out" message.

I mean it's not really "lying" (because it did time out, you just don't know why it timed out), it's just being a bit vague :P
